import {
  ProviderAccount,
  UnifiedProduct,
  Transaction,
  VerifiedActivityEvent,
  GalleryPreset,
} from "./types";

export const INITIAL_PROVIDERS: ProviderAccount[] = [
  {
    id: "acc_stripe_main",
    provider: "stripe",
    accountName: "Stripe Primary (US/Global)",
    accountId: "acct_1NZ4892StripeUS",
    connectedAt: "2026-01-15T10:00:00Z",
    lastSyncedAt: "2026-08-23T17:12:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "refunds", "countries"],
    isSandbox: false,
  },
  {
    id: "acc_polar_oss",
    provider: "polar",
    accountName: "Polar Open Source & Crowdfunding",
    accountId: "org_polar_8912x",
    connectedAt: "2026-02-10T14:30:00Z",
    lastSyncedAt: "2026-08-23T17:05:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "countries"],
    isSandbox: false,
  },
  {
    id: "acc_revenuecat_mobile",
    provider: "revenuecat",
    accountName: "RevenueCat iOS/Android Fleet",
    accountId: "app_rc_9941a8",
    connectedAt: "2026-03-01T09:15:00Z",
    lastSyncedAt: "2026-08-23T17:00:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "refunds"],
    isSandbox: false,
  },
  {
    id: "acc_appstore_connect",
    provider: "app_store",
    accountName: "Apple App Store Connect (Global)",
    accountId: "asc_vendor_88204",
    connectedAt: "2026-03-12T11:20:00Z",
    lastSyncedAt: "2026-08-23T16:45:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "refunds", "countries"],
    isSandbox: false,
  },
  {
    id: "acc_lemonsqueezy_store",
    provider: "lemonsqueezy",
    accountName: "Lemon Squeezy Digital Assets",
    accountId: "ls_store_44019",
    connectedAt: "2026-05-18T16:00:00Z",
    lastSyncedAt: "2026-08-23T16:50:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "refunds", "countries"],
    isSandbox: false,
  },
  {
    id: "acc_dodopayments_merchant",
    provider: "dodopayments",
    accountName: "Dodo Payments Merchant",
    accountId: "dodo_merch_77190",
    connectedAt: "2026-06-01T10:00:00Z",
    lastSyncedAt: "2026-08-23T17:15:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "refunds", "countries"],
    isSandbox: false,
  },
  {
    id: "acc_paddle_billing",
    provider: "paddle",
    accountName: "Paddle Billing Merchant",
    accountId: "pad_merch_88201",
    connectedAt: "2026-06-15T12:00:00Z",
    lastSyncedAt: "2026-08-23T17:20:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "refunds", "countries"],
    isSandbox: false,
  },
  {
    id: "acc_gumroad_store",
    provider: "gumroad",
    accountName: "Gumroad Digital Store",
    accountId: "gum_store_66190",
    connectedAt: "2026-07-01T10:00:00Z",
    lastSyncedAt: "2026-08-23T17:30:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "refunds", "countries"],
    isSandbox: false,
  },
  {
    id: "acc_creem_merchant",
    provider: "creem",
    accountName: "Creem Store",
    accountId: "creem_store_99312",
    connectedAt: "2026-07-01T14:00:00Z",
    lastSyncedAt: "2026-08-23T17:25:00Z",
    status: "active",
    metricsSupported: ["revenue", "sales", "customers", "subscriptions", "refunds", "countries"],
    isSandbox: false,
  },
];

export const INITIAL_PRODUCTS: UnifiedProduct[] = [
  {
    id: "prod_reel_player",
    name: "Reel Player Pro",
    slug: "reel-player-pro",
    category: "Desktop App",
    primaryCurrency: "USD",
    totalRevenue: 64280,
    totalSales: 1284,
    totalCustomers: 1210,
    activeSubscriptions: 480,
    mrr: 4320,
    totalRefunds: 8,
    avgOrderValue: 50.06,
    growthYoY: "+84.2%",
    createdAt: "2026-01-18",
    providers: [
      {
        provider: "stripe",
        externalProductId: "prod_stripe_reel_01",
        externalProductName: "Reel Player macOS Lifetime & Sub",
        revenue: 41200,
        salesCount: 820,
        activeSubscriptions: 310,
        refunds: 5,
        lastSaleAt: "2026-08-23T16:42:00Z",
      },
      {
        provider: "polar",
        externalProductId: "prod_polar_reel_02",
        externalProductName: "Reel Player GitHub Early Bird License",
        revenue: 23080,
        salesCount: 464,
        activeSubscriptions: 170,
        refunds: 3,
        lastSaleAt: "2026-08-23T15:10:00Z",
      },
    ],
    channels: [
      {
        provider: "stripe",
        externalProductId: "prod_stripe_reel_01",
        externalProductName: "Reel Player macOS Lifetime & Sub",
        revenue: 41200,
        salesCount: 820,
        activeSubscriptions: 310,
        refunds: 5,
        lastSaleAt: "2026-08-23T16:42:00Z",
      },
      {
        provider: "polar",
        externalProductId: "prod_polar_reel_02",
        externalProductName: "Reel Player GitHub Early Bird License",
        revenue: 23080,
        salesCount: 464,
        activeSubscriptions: 170,
        refunds: 3,
        lastSaleAt: "2026-08-23T15:10:00Z",
      },
    ],
  },
  {
    id: "prod_screenflow_kit",
    name: "ScreenFlow Video UI Kit",
    slug: "screenflow-ui-kit",
    category: "Digital Asset",
    primaryCurrency: "USD",
    totalRevenue: 28450,
    totalSales: 569,
    totalCustomers: 540,
    activeSubscriptions: 0,
    mrr: 0,
    totalRefunds: 2,
    avgOrderValue: 50.0,
    growthYoY: "+42.1%",
    createdAt: "2026-03-02",
    providers: [
      {
        provider: "lemonsqueezy",
        externalProductId: "ls_prod_kit_99",
        externalProductName: "ScreenFlow Design Kit & Components",
        revenue: 19850,
        salesCount: 397,
        refunds: 1,
        lastSaleAt: "2026-08-23T14:20:00Z",
      },
      {
        provider: "polar",
        externalProductId: "polar_prod_kit_44",
        externalProductName: "ScreenFlow Components Source Bundle",
        revenue: 8600,
        salesCount: 172,
        refunds: 1,
        lastSaleAt: "2026-08-22T19:40:00Z",
      },
    ],
    channels: [
      {
        provider: "lemonsqueezy",
        externalProductId: "ls_prod_kit_99",
        externalProductName: "ScreenFlow Design Kit & Components",
        revenue: 19850,
        salesCount: 397,
        refunds: 1,
        lastSaleAt: "2026-08-23T14:20:00Z",
      },
      {
        provider: "polar",
        externalProductId: "polar_prod_kit_44",
        externalProductName: "ScreenFlow Components Source Bundle",
        revenue: 8600,
        salesCount: 172,
        refunds: 1,
        lastSaleAt: "2026-08-22T19:40:00Z",
      },
    ],
  },
  {
    id: "prod_hyperfocus_ios",
    name: "HyperFocus Mobile & Watch App",
    slug: "hyperfocus-app",
    category: "Mobile App",
    primaryCurrency: "USD",
    totalRevenue: 46000,
    totalSales: 1910,
    totalCustomers: 1780,
    activeSubscriptions: 820,
    mrr: 4920,
    totalRefunds: 12,
    avgOrderValue: 24.08,
    growthYoY: "+118.4%",
    createdAt: "2026-02-14",
    providers: [
      {
        provider: "revenuecat",
        externalProductId: "rc_sub_hyperfocus_monthly",
        externalProductName: "HyperFocus Pro Subscriptions (Unified)",
        revenue: 33400,
        salesCount: 1390,
        activeSubscriptions: 610,
        refunds: 8,
        lastSaleAt: "2026-08-23T16:55:00Z",
      },
      {
        provider: "app_store",
        externalProductId: "asc_iap_hyperfocus_lifetime",
        externalProductName: "HyperFocus iOS Lifetime Unlock",
        revenue: 12600,
        salesCount: 520,
        activeSubscriptions: 210,
        refunds: 4,
        lastSaleAt: "2026-08-23T13:45:00Z",
      },
    ],
    channels: [
      {
        provider: "revenuecat",
        externalProductId: "rc_sub_hyperfocus_monthly",
        externalProductName: "HyperFocus Pro Subscriptions (Unified)",
        revenue: 33400,
        salesCount: 1390,
        activeSubscriptions: 610,
        refunds: 8,
        lastSaleAt: "2026-08-23T16:55:00Z",
      },
      {
        provider: "app_store",
        externalProductId: "asc_iap_hyperfocus_lifetime",
        externalProductName: "HyperFocus iOS Lifetime Unlock",
        revenue: 12600,
        salesCount: 520,
        activeSubscriptions: 210,
        refunds: 4,
        lastSaleAt: "2026-08-23T13:45:00Z",
      },
    ],
  },
  {
    id: "prod_fastapi_saas_kit",
    name: "FastSaaS Next.js + Neon Template",
    slug: "fastsaas-boilerplate",
    category: "SaaS",
    primaryCurrency: "USD",
    totalRevenue: 37900,
    totalSales: 379,
    totalCustomers: 365,
    activeSubscriptions: 45,
    mrr: 890,
    totalRefunds: 1,
    avgOrderValue: 100.0,
    growthYoY: "+65.0%",
    createdAt: "2026-04-10",
    providers: [
      {
        provider: "stripe",
        externalProductId: "stripe_prod_fastsaas_lic",
        externalProductName: "FastSaaS All-Access License",
        revenue: 29900,
        salesCount: 299,
        activeSubscriptions: 35,
        refunds: 1,
        lastSaleAt: "2026-08-23T11:05:00Z",
      },
      {
        provider: "polar",
        externalProductId: "polar_prod_fastsaas_sponsor",
        externalProductName: "FastSaaS Open Collective Tier",
        revenue: 8000,
        salesCount: 80,
        activeSubscriptions: 10,
        refunds: 0,
        lastSaleAt: "2026-08-21T18:10:00Z",
      },
    ],
    channels: [
      {
        provider: "stripe",
        externalProductId: "stripe_prod_fastsaas_lic",
        externalProductName: "FastSaaS All-Access License",
        revenue: 29900,
        salesCount: 299,
        activeSubscriptions: 35,
        refunds: 1,
        lastSaleAt: "2026-08-23T11:05:00Z",
      },
      {
        provider: "polar",
        externalProductId: "polar_prod_fastsaas_sponsor",
        externalProductName: "FastSaaS Open Collective Tier",
        revenue: 8000,
        salesCount: 80,
        activeSubscriptions: 10,
        refunds: 0,
        lastSaleAt: "2026-08-21T18:10:00Z",
      },
    ],
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // 2026-08-23 Transactions
  {
    id: "tx_99812",
    provider: "stripe",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "sarah.k@designsystem.co",
    customerCountry: "United States",
    amount: 59.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-23T16:42:00Z",
  },
  {
    id: "tx_99811",
    provider: "revenuecat",
    productId: "prod_hyperfocus_ios",
    productName: "HyperFocus Mobile & Watch App",
    customerEmail: "alex.m@tokyo.jp",
    customerCountry: "Japan",
    amount: 29.99,
    currency: "USD",
    type: "subscription",
    status: "succeeded",
    timestamp: "2026-08-23T16:30:00Z",
  },
  {
    id: "tx_99810",
    provider: "polar",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "lucas@devteam.berlin",
    customerCountry: "Germany",
    amount: 49.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-23T15:10:00Z",
  },
  {
    id: "tx_99809",
    provider: "lemonsqueezy",
    productId: "prod_screenflow_kit",
    productName: "ScreenFlow Video UI Kit",
    customerEmail: "marcus.v@studio.uk",
    customerCountry: "United Kingdom",
    amount: 50.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-23T14:20:00Z",
  },
  {
    id: "tx_99808",
    provider: "app_store",
    productId: "prod_hyperfocus_ios",
    productName: "HyperFocus Mobile & Watch App",
    customerEmail: "emma.watson@sf.io",
    customerCountry: "United States",
    amount: 19.99,
    currency: "USD",
    type: "subscription",
    status: "succeeded",
    timestamp: "2026-08-23T13:45:00Z",
  },
  {
    id: "tx_99807",
    provider: "stripe",
    productId: "prod_fastapi_saas_kit",
    productName: "FastSaaS Next.js + Neon Template",
    customerEmail: "priya.sharma@bangalore.in",
    customerCountry: "India",
    amount: 129.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-23T11:05:00Z",
  },
  // 2026-08-22 Transactions
  {
    id: "tx_99806",
    provider: "stripe",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "claire.d@paris.fr",
    customerCountry: "France",
    amount: 59.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-22T20:15:00Z",
  },
  {
    id: "tx_99805",
    provider: "polar",
    productId: "prod_screenflow_kit",
    productName: "ScreenFlow Video UI Kit",
    customerEmail: "kenji.s@osaka.jp",
    customerCountry: "Japan",
    amount: 50.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-22T19:40:00Z",
  },
  {
    id: "tx_99804",
    provider: "revenuecat",
    productId: "prod_hyperfocus_ios",
    productName: "HyperFocus Mobile & Watch App",
    customerEmail: "liam.o@dublin.ie",
    customerCountry: "Ireland",
    amount: 29.99,
    currency: "USD",
    type: "subscription",
    status: "succeeded",
    timestamp: "2026-08-22T14:10:00Z",
  },
  {
    id: "tx_99803",
    provider: "stripe",
    productId: "prod_fastapi_saas_kit",
    productName: "FastSaaS Next.js + Neon Template",
    customerEmail: "david.b@austin.io",
    customerCountry: "United States",
    amount: 129.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-22T10:30:00Z",
  },
  // 2026-08-21 Transactions
  {
    id: "tx_99802",
    provider: "polar",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "matteo.r@milan.it",
    customerCountry: "Italy",
    amount: 49.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-21T18:50:00Z",
  },
  {
    id: "tx_99801",
    provider: "polar",
    productId: "prod_fastapi_saas_kit",
    productName: "FastSaaS Next.js + Neon Template",
    customerEmail: "felix.k@zurich.ch",
    customerCountry: "Switzerland",
    amount: 129.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-21T18:10:00Z",
  },
  {
    id: "tx_99800",
    provider: "lemonsqueezy",
    productId: "prod_screenflow_kit",
    productName: "ScreenFlow Video UI Kit",
    customerEmail: "hannah.t@toronto.ca",
    customerCountry: "Canada",
    amount: 50.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-21T15:25:00Z",
  },
  {
    id: "tx_99799",
    provider: "app_store",
    productId: "prod_hyperfocus_ios",
    productName: "HyperFocus Mobile & Watch App",
    customerEmail: "noah.j@sydney.au",
    customerCountry: "Australia",
    amount: 19.99,
    currency: "USD",
    type: "subscription",
    status: "succeeded",
    timestamp: "2026-08-21T09:12:00Z",
  },
  // 2026-08-20 Transactions
  {
    id: "tx_99798",
    provider: "stripe",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "sofia.g@madrid.es",
    customerCountry: "Spain",
    amount: 59.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-20T21:40:00Z",
  },
  {
    id: "tx_99797",
    provider: "lemonsqueezy",
    productId: "prod_screenflow_kit",
    productName: "ScreenFlow Video UI Kit",
    customerEmail: "oliver.w@london.uk",
    customerCountry: "United Kingdom",
    amount: 50.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-20T16:05:00Z",
  },
  {
    id: "tx_99796",
    provider: "revenuecat",
    productId: "prod_hyperfocus_ios",
    productName: "HyperFocus Mobile & Watch App",
    customerEmail: "erik.l@stockholm.se",
    customerCountry: "Sweden",
    amount: 29.99,
    currency: "USD",
    type: "subscription",
    status: "succeeded",
    timestamp: "2026-08-20T11:20:00Z",
  },
  // 2026-08-19 Transactions
  {
    id: "tx_99795",
    provider: "stripe",
    productId: "prod_fastapi_saas_kit",
    productName: "FastSaaS Next.js + Neon Template",
    customerEmail: "carlos.m@sao-paulo.br",
    customerCountry: "Brazil",
    amount: 129.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-19T17:35:00Z",
  },
  {
    id: "tx_99794",
    provider: "polar",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "bjorn.h@oslo.no",
    customerCountry: "Norway",
    amount: 49.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-19T14:15:00Z",
  },
  {
    id: "tx_99793",
    provider: "app_store",
    productId: "prod_hyperfocus_ios",
    productName: "HyperFocus Mobile & Watch App",
    customerEmail: "yuki.t@kyoto.jp",
    customerCountry: "Japan",
    amount: 19.99,
    currency: "USD",
    type: "subscription",
    status: "succeeded",
    timestamp: "2026-08-19T08:45:00Z",
  },
  // 2026-08-18 Transactions
  {
    id: "tx_99792",
    provider: "stripe",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "charlotte.b@chicago.us",
    customerCountry: "United States",
    amount: 59.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-18T19:22:00Z",
  },
  {
    id: "tx_99791",
    provider: "lemonsqueezy",
    productId: "prod_screenflow_kit",
    productName: "ScreenFlow Video UI Kit",
    customerEmail: "arthur.p@amsterdam.nl",
    customerCountry: "Netherlands",
    amount: 50.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-18T13:40:00Z",
  },
  {
    id: "tx_99790",
    provider: "revenuecat",
    productId: "prod_hyperfocus_ios",
    productName: "HyperFocus Mobile & Watch App",
    customerEmail: "grace.l@singapore.sg",
    customerCountry: "Singapore",
    amount: 29.99,
    currency: "USD",
    type: "subscription",
    status: "succeeded",
    timestamp: "2026-08-18T10:15:00Z",
  },
  // 2026-08-17 Transactions
  {
    id: "tx_99789",
    provider: "polar",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    customerEmail: "lars.v@copenhagen.dk",
    customerCountry: "Denmark",
    amount: 49.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-17T18:05:00Z",
  },
  {
    id: "tx_99788",
    provider: "stripe",
    productId: "prod_fastapi_saas_kit",
    productName: "FastSaaS Next.js + Neon Template",
    customerEmail: "devon.k@seattle.us",
    customerCountry: "United States",
    amount: 129.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-17T14:50:00Z",
  },
  {
    id: "tx_99787",
    provider: "lemonsqueezy",
    productId: "prod_screenflow_kit",
    productName: "ScreenFlow Video UI Kit",
    customerEmail: "elena.r@vienna.at",
    customerCountry: "Austria",
    amount: 50.0,
    currency: "USD",
    type: "one_time",
    status: "succeeded",
    timestamp: "2026-08-17T11:30:00Z",
  },
];

export const INITIAL_ACTIVITY_EVENTS: VerifiedActivityEvent[] = [
  {
    id: "evt_act_01",
    type: "revenue_crossed",
    title: "Lifetime Revenue Crossed $180,000",
    description: "Consolidated verified revenue across Stripe, Polar, RevenueCat, App Store & Lemon Squeezy.",
    metricValue: 181830,
    formattedMetric: "$181,830",
    currency: "USD",
    provider: "stripe",
    timestamp: "2026-08-23T16:42:00Z",
    hasShared: false,
    socialCopyVariants: {
      minimal: "indic8 business portfolio just crossed $180,000 in authentic revenue.",
      story: "Built as independent micro-tools, our combined products just crossed $180,000 in gross sales across 5 payment platforms.",
      founder: "Started shipping code in January. Today our developer portfolio crossed $180k across Stripe, Polar, and App Store.",
    },
  },
  {
    id: "evt_act_02",
    type: "sales_crossed",
    title: "Reel Player Pro Reached 1,280 Sales",
    description: "820 units on Stripe + 464 developer units on Polar.",
    metricValue: 1284,
    formattedMetric: "1,284 Sales",
    currency: "USD",
    productId: "prod_reel_player",
    productName: "Reel Player Pro",
    provider: "stripe",
    timestamp: "2026-08-23T16:42:00Z",
    hasShared: true,
    socialCopyVariants: {
      minimal: "Reel Player Pro just passed 1,280 sales.",
      story: "1,284 creators and engineers now use Reel Player to record their screen interactions.",
      founder: "Started Reel Player as a weekend prototype. It just passed 1,280 authentic sales across Stripe & Polar.",
    },
  },
  {
    id: "evt_act_03",
    type: "best_day",
    title: "All-Time Highest Revenue Day: $12,550",
    description: "Daily record set on August 23 across all connected payment channels.",
    metricValue: 12550,
    formattedMetric: "$12,550",
    currency: "USD",
    provider: "stripe",
    timestamp: "2026-08-23T17:00:00Z",
    hasShared: false,
    socialCopyVariants: {
      minimal: "Today was our best revenue day yet: $12,550.",
      story: "Recorded $12,550 in 24 hours across our software suite. Grateful for everyone supporting indie software.",
      founder: "Just logged our biggest single day: $12,550 processed across Stripe, Polar, and RevenueCat.",
    },
  },
];

export const GALLERY_PRESETS: GalleryPreset[] = [
  {
    id: "preset_rev_100k",
    title: "6-Figure Revenue Milestone",
    category: "revenue",
    description: "Celebrating verified $100,000+ consolidated business revenue.",
    numericValue: 181830,
    metricLabel: "Total Verified Revenue",
    subtext: "Consolidated across Stripe, Polar & RevenueCat",
    currencySymbol: "$",
    currencyCode: "USD",
    prefix: "",
    suffix: "",
    growthDelta: "+124% YoY",
    verifiedSource: "stripe",
    templateStyle: "stripe-card",
    backdropId: "midnight-obsidian",
    frameType: "keynote",
    accentColor: "#635BFF",
    aspectRatio: "16:9",
    socialCopy: {
      minimal: "indic8 verified: Just crossed $180,000 in total revenue.",
      story: "Built in public with zero VC funding: our portfolio just passed $180,000 across 5 payment platforms.",
      founder: "6 figures in software sales unlocked. Thanks to every single customer who believed in what we're building.",
    },
  },
  {
    id: "preset_prod_reel",
    title: "Reel Player 1,000+ Sales",
    category: "sales",
    description: "Single product sales milestone for Reel Player Pro.",
    numericValue: 1284,
    metricLabel: "Total Units Sold",
    subtext: "Reel Player Pro · Stripe + Polar Sync",
    currencySymbol: "",
    currencyCode: "USD",
    prefix: "",
    suffix: " Sales",
    growthDelta: "+84% Growth",
    verifiedSource: "polar",
    templateStyle: "polar-frost",
    backdropId: "deep-ocean",
    frameType: "safari",
    accentColor: "#0062FF",
    aspectRatio: "1:1",
    socialCopy: {
      minimal: "Reel Player Pro crossed 1,280 sales.",
      story: "From a weekend hack to 1,284 paying developers. Reel Player just hit its biggest milestone.",
      founder: "1,284 licenses sold. Built Reel Player to solve my own screen recording workflow, and it resonated.",
    },
  },
  {
    id: "preset_daily_record",
    title: "Record Day: $12.5k in 24h",
    category: "recap",
    description: "Single-day highest revenue recap across all channels.",
    numericValue: 12550,
    metricLabel: "Daily Revenue Record",
    subtext: "Today across 4 connected platforms",
    currencySymbol: "$",
    currencyCode: "USD",
    prefix: "",
    suffix: "",
    growthDelta: "+210% vs avg",
    verifiedSource: "stripe",
    templateStyle: "minimalist",
    backdropId: "neon-cyberpunk",
    frameType: "device-iphone",
    accentColor: "#10B981",
    aspectRatio: "9:16",
    socialCopy: {
      minimal: "Best day yet: $12,550 processed today.",
      story: "$12.5k in 24 hours. The compounding power of multiple connected products.",
      founder: "Today was our highest revenue day on record ($12,550). Every number verified via indic8.",
    },
  },
  {
    id: "preset_mrr_growth",
    title: "Monthly Recurring Revenue",
    category: "revenue",
    description: "Active subscription MRR recap across mobile and desktop apps.",
    numericValue: 10730,
    metricLabel: "Monthly Recurring Revenue (MRR)",
    subtext: "1,445 active paying subscribers",
    currencySymbol: "$",
    currencyCode: "USD",
    prefix: "",
    suffix: " /mo",
    growthDelta: "+38% MoM",
    verifiedSource: "revenuecat",
    templateStyle: "apple-glass",
    backdropId: "supernova-amber",
    frameType: "browser-clean",
    accentColor: "#F59E0B",
    aspectRatio: "16:9",
    socialCopy: {
      minimal: "MRR crossed $10,700/mo across our apps.",
      story: "Passionate subscribers generating $10.7k in predictable recurring revenue every month.",
      founder: "Hit $10,730 in MRR. 1,445 subscribers across iOS, Android, and macOS. Subscription revenue hits different.",
    },
  },
];
